<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SMAMQC8" failures="1" tests="14" name="runner.TestRunner" time="157.121" errors="0" timestamp="2024-04-14T08:44:09 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="11.818"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="9.669"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="7.565"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="9.700"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="18.047"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="13.215"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="7.940"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="12.901"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="12.396"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="12.467"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="8.081"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="13.604"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="9.330"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="10.388">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at stepdefinitions.Login.user_should_get_a_proper_warning_message_about_credentails_mismatch(Login.java:106)
at âœ½.User should get a proper warning message about credentails mismatch(file:///C:/Users/DELL/eclipse-workspace/CucumberWorkspace/TutorialsNinjaCucumberProject/src/test/resources/features/Login.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
